[project]
name = "backup-telegram-saved-messages"
version = "0.1.0"
description = "telegram bot to backup saved messages"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.1.0",
    "smbprotocol>=1.15.0",
    "telethon>=1.40.0",
]
